### ISSUE TITLE
Рисование графиков представленных в отчетах ГИБДД

### ISSUE THREAD

**Issue by mad** [egor1989/GAI#1]
Примеры лежат тут в PDF

http://www.gibdd.ru/info/stat/

**Comment by mad** [comment]
@disovi предлагает использовать flotr2

**Comment by ruXlab** [comment]
Спасибо. Кажется, я понял что нужно

**Comment by ruXlab** [comment]
Для графиков то? Это же не критично что использовать. Google charts https://developers.google.com/chart/ .

**Comment by mad** [comment]
Можно и его. Они же могут быть интерактивные?

**Comment by ruXlab** [comment]
да, можно примеры посмотреть - нормальненько.
Мало того, из одно и того же datasource можно (почти) любые представления
лепить

On Thu, Sep 20, 2012 at 6:29 PM, Pavel notifications@github.com wrote:

> Можно и его. Они же могут быть интерактивные?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/egor1989/GAI/issues/1#issuecomment-8730030.

## 

C уважением, Руслан
  post4ruX@gmail.com
  http://ruX.pp.ru
  http://crazygeo.com
